---
title: "problem_2"

output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r, message=FALSE, include = FALSE}
#loading data
library(p8105.datasets)
library(tidyverse)
library(plotly)
data("instacart")

instacart <- instacart %>% as_tibble()
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A
    
```{r}
#first plot, using my plot from hw3
instacart %>%
  count(aisle) %>%
  filter(n > 10000) %>%
  mutate(aisle = fct_reorder(aisle, n),
         text_label = str_c('Aisle: ', aisle,
                            '\nItems Ordered:', n)) %>%
  plot_ly(
    x = ~aisle, y = ~n, type = 'scatter', mode = 'markers',
    text = ~ text_label, alpha = 0.5)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
#want to see the number/types of baking ingredients ordered in pantry department
instacart %>%
  filter(department == 'pantry',
         aisle == 'baking ingredients') %>%
  group_by(product_name) %>%
  count(product_name) %>%
  #not sure why my fct_reorder doesn't work? I've had trouble applying it to other assignments too.
#  mutate(product_name = fct_reorder(product_name, n, .desc = FALSE)) %>%
  plot_ly(x = ~product_name, y = ~n, color = ~product_name,
          type = 'bar', colors = 'viridis')
```

### Chart C

```{r}

```


